version: '3.8'

services:
  bus:
    image: jrgiadach/soabus:v1
    container_name: soabus
    ports:
      - "5001:5000"
    restart: always
  
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
